Repository alberto-linao/formsly.io, pull requests merged in 2024-09, with the labels that each got.

#1188 Lance/add human resources viewer group
  backend/api/get.ts
  components/Layout/AppLayout/Navbar/NavLink.tsx
  components/TechnicalAssessmentCreateQuestionPage/TechnicalAssessmentViewQuestionPage.tsx
  pages/[teamName]/requests/application-information-spreadsheet-view.tsx
  pages/[teamName]/requests/background-check-spreadsheet-view.tsx
  pages/[teamName]/requests/director-interview-spreadsheet-view.tsx
  pages/[teamName]/requests/hr-phone-interview-spreadsheet-view.tsx
  pages/[teamName]/requests/job-offer-spreadsheet-view.tsx
  pages/[teamName]/requests/technical-interview-1-spreadsheet-view.tsx
  pages/[teamName]/requests/technical-interview-2-spreadsheet-view.tsx
  pages/[teamName]/requests/trade-test-spreadsheet-view.tsx
  pages/[teamName]/technical-question/[questionnaireId]/create.tsx
  pages/[teamName]/technical-question/[questionnaireId]/index.tsx
  schema.sql
Labels: enhancement

#1189 add note to assignee if employee not found
  components/CreateITAssetRequestPage.tsx/CreateITAssetRequestPage.tsx
  components/EditITAssetRequestPage/EditITAssetRequestPage.tsx
Labels: enhancement

#1191 Lance/fix-capitalize-names
  utils/string.ts
Labels: bug

#1190 fix mismatch jira form fields
  utils/jira/functions.ts
Labels: bug

#1192 Lance/fixed-rls-for-HR-that-is-also-an-approver
  schema.sql
Labels: bug

#1193 Lance/fix-hr-phone-interview-spreadsheet-page
  utils/string.ts
Labels: bug

#1194 Lance/add trim and remove double spaces for text field type
  backend/api/post.ts
Labels: enhancement

#1196 Lance/fix-scheduling-time
  components/ApplicationProgressPage/SchedulingCalendar.tsx
Labels: bug

#1197 Update HR Analytics
  schema.sql
Labels: bug, enhancement

#1195 Lance/fix-mismatch-casing-of-applicant-email
  schema.sql
Labels: enhancement

#1199 log env on build
  next.config.js
Labels: bug

#1200 add supabase.ts
  next.config.js
  utils/supabase.ts
Labels: bug
