Repository alberto-linao/formsly.io, pull requests merged in 2024-10, with the labels that each got.

#1204 Jc/fix application information approval
  additional.d.ts
  backend/api/get.ts
  components/ApplicationInformationV1RequestPage/ApplicationInformationV1RequestPage.tsx
  components/Chart/HorizontalBarChart.tsx
  components/Chart/LineChart.tsx
  components/Chart/PieChart.tsx
  components/Chart/StackedBarChart.tsx
  components/Chart/VerticalBarChart.tsx
  components/ExportToPDF/ExportToPdf.tsx
  components/Memo/ExportMemoToPdf.tsx
  components/Memo/MemoPDF.tsx
  components/TicketAdminAnalytics/StackedBarChart.tsx
  pages/api/jira/create-recruitment-ticket.ts
Labels: bug

#1206 Revert rollback
  backend/api/get.ts
  backend/api/post.ts
  components/ApplicationInformationV1RequestPage/ApplicationInformationV1RequestPage.tsx
  components/ApplicationProgressPage/SchedulingCalendar.tsx
  components/CreateITAssetRequestPage.tsx/CreateITAssetRequestPage.tsx
  components/EditITAssetRequestPage/EditITAssetRequestPage.tsx
  components/Layout/AppLayout/Navbar/NavLink.tsx
  components/Memo/MemoPDF.tsx
  components/TechnicalAssessmentCreateQuestionPage/TechnicalAssessmentViewQuestionPage.tsx
  next.config.js
  package-lock.json
  pages/[teamName]/requests/application-information-spreadsheet-view.tsx
  pages/[teamName]/requests/background-check-spreadsheet-view.tsx
  pages/[teamName]/requests/director-interview-spreadsheet-view.tsx
  pages/[teamName]/requests/hr-phone-interview-spreadsheet-view.tsx
  pages/[teamName]/requests/job-offer-spreadsheet-view.tsx
  pages/[teamName]/requests/technical-interview-1-spreadsheet-view.tsx
  pages/[teamName]/requests/technical-interview-2-spreadsheet-view.tsx
  pages/[teamName]/requests/trade-test-spreadsheet-view.tsx
  pages/[teamName]/technical-question/[questionnaireId]/create.tsx
  pages/[teamName]/technical-question/[questionnaireId]/index.tsx
  pages/api/jira/create-ticket.ts
  schema.sql
  utils/constant.ts
  utils/jira/functions.ts
  utils/string.ts
  utils/supabase/index.ts
Labels: bug

#1207 Lance/fix assigned hr in scheduling
  backend/api/get.ts
  components/ApplicationProgressPage/HRPhoneInterview.tsx
  components/ApplicationProgressPage/SchedulingCalendar.tsx
  pages/api/jira/create-ticket.ts
  schema.sql
Labels: bug, enhancement

#1208 Lance/HR Feature update
  components/ApplicationInformationSpreadsheetView/ApplicationInformationFilterMenu.tsx
  components/ApplicationProgressPage/SchedulingCalendar.tsx
  components/BackgroundCheckSpreadsheetView/BackgroundCheckFilterMenu.tsx
  components/CreateTechnicalAssessmentRequestPage/CreateTechnicalAssessmentRequestPage.tsx
  components/DirectorInterviewSpreadsheetView/DirectorInterviewFilterMenu.tsx
  components/DirectorInterviewSpreadsheetView/DirectorInterviewSpreadsheetTable/DirectorInterviewMainTableRow.tsx
  components/DirectorInterviewSpreadsheetView/DirectorInterviewSpreadsheetTable/DirectorInterviewSpreadsheetTable.tsx
  components/DirectorInterviewSpreadsheetView/DirectorInterviewSpreadsheetView.tsx
  components/HRPhoneInterviewSpreadsheetView/HRPhoneInterviewFilterMenu.tsx
  components/JobOfferSpreadsheetView/JobOfferFilterMenu.tsx
  components/TechnicalAssessmentRequestPage/TechnicalAssessmentRequestPage.tsx
  components/TechnicalInterviewSpreadsheetView/TechnicalInterviewFilterMenu.tsx
  components/TechnicalInterviewSpreadsheetView/TechnicalInterviewSpreadsheetTable/TechnicalInterviewMainTableRow.tsx
  components/TechnicalInterviewSpreadsheetView/TechnicalInterviewSpreadsheetTable/TechnicalInterviewSpreadsheetTable.tsx
  components/TechnicalInterviewSpreadsheetView/TechnicalInterviewSpreadsheetView.tsx
  components/TradeTestSpreadsheetView/TradeTestFilterMenu.tsx
  components/TradeTestSpreadsheetView/TradeTestSpreadsheetTable/TradeTestMainTableRow.tsx
  components/TradeTestSpreadsheetView/TradeTestSpreadsheetTable/TradeTestSpreadsheetTable.tsx
  components/TradeTestSpreadsheetView/TradeTestSpreadsheetView.tsx
  schema.sql
  utils/constant.ts
  utils/types.ts
Labels: bug, enhancement

#1209 Lance/Fix technical next step restriction and add copy meeting link
  components/DirectorInterviewSpreadsheetView/DirectorInterviewSpreadsheetTable/DirectorInterviewMainTableRow.tsx
  components/TechnicalAssessmentRequestPage/TechnicalAssessmentRequestPage.tsx
  components/TechnicalInterviewSpreadsheetView/TechnicalInterviewSpreadsheetTable/TechnicalInterviewMainTableRow.tsx
  components/TradeTestSpreadsheetView/TradeTestSpreadsheetTable/TradeTestMainTableRow.tsx
Labels: enhancement

#1210 Lance/fix scheduling sequence
  components/ApplicationProgressPage/SchedulingCalendar.tsx
Labels: bug

#1211 Lance/Fix rls for removed hr member and add override condition
  components/DirectorInterviewSpreadsheetView/DirectorInterviewSpreadsheetTable/DirectorInterviewMainTableRow.tsx
  components/HRPhoneInterviewSpreadsheetView/HRPhoneInterviewSpreadsheetTable/HRPhoneInterviewMainTableRow.tsx
  components/JobOfferSpreadsheetView/JobOfferSpreadsheetTable/JobOfferMainTableRow.tsx
  components/TechnicalInterviewSpreadsheetView/TechnicalInterviewSpreadsheetTable/TechnicalInterviewMainTableRow.tsx
  components/TradeTestSpreadsheetView/TradeTestSpreadsheetTable/TradeTestMainTableRow.tsx
  schema.sql
Labels: bug, enhancement

#1212 Lance/Update scheduling flow
  backend/api/post.ts
  backend/api/update.ts
  components/ApplicationProgressPage/SchedulingCalendar.tsx
  components/TechnicalAssessmentRequestPage/TechnicalAssessmentRequestPage.tsx
  schema.sql
  utils/database.ts
Labels: bug, enhancement

#1213 fix jira automation in it asset
  components/ITAssetRequestPage/ITAssetRequestPage.tsx
Labels: bug
